CREATE TABLE IF NOT EXISTS fuentes (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rss_url VARCHAR(255) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS update_fuentes_updated_at
AFTER UPDATE ON fuentes
FOR EACH ROW
BEGIN
    UPDATE fuentes SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
